# This file was generated by GoReleaser. DO NOT EDIT.
cask "flow" do
  version "0.4.0"

  on_macos do
    sha256 "96ff47093bb63e898b7702bf8cf2fc433a89978cddef39b55a27e427d1b80269"
    url "https://github.com/idosaban-scaleops/flow/releases/download/v#{version}/flow_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "8fd43ead085c4317bf0a6d79ddc92f57d3328feee3bfaac08f076e5b85a81891"
      url "https://github.com/idosaban-scaleops/flow/releases/download/v#{version}/flow_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d2ef4afa7eb844d516140446d272f1e9a1ad62f60d42e922b508c86c8c8b6545"
      url "https://github.com/idosaban-scaleops/flow/releases/download/v#{version}/flow_#{version}_linux_amd64.tar.gz"
    end
  end

  name "flow"
  desc "A personal workflow CLI for ticket-driven development"
  homepage "https://github.com/idosaban-scaleops/flow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flow"
  manpage "man/man1/flow.1"
  bash_completion "completions/flow.bash"
  fish_completion "completions/flow.fish"
  zsh_completion "completions/flow.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flow"]
    end
  end

  # No zap stanza required
end
