# This file was generated by GoReleaser. DO NOT EDIT.
cask "flow" do
  version "0.1.0"

  on_macos do
    sha256 "8ff9f6b279fab770472e5de803fec3fc652086601a320264fcb0a6115cbafef0"
    url "https://github.com/idosaban-scaleops/flow/releases/download/v#{version}/flow_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "9f32ff575152708595cd636229006baab9a081ff8a4631cc79126aafbdb65eca"
      url "https://github.com/idosaban-scaleops/flow/releases/download/v#{version}/flow_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2d39c198bb23c55c9c51d8f1b338407d8c9f406fce321913966774fd8920b136"
      url "https://github.com/idosaban-scaleops/flow/releases/download/v#{version}/flow_#{version}_linux_amd64.tar.gz"
    end
  end

  name "flow"
  desc "A personal workflow CLI for ticket-driven development"
  homepage "https://github.com/idosaban-scaleops/flow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flow"
  manpage "man/man1/flow.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flow"]
    end
  end
  generate_completions_from_executable "flow", "completions",
    shell_parameter_format: :cobra

  # No zap stanza required
end
