# This file was generated by GoReleaser. DO NOT EDIT.
cask "flow" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/flow"], must_succeed: false
    end
  end

  version "0.5.2"

  on_macos do
    sha256 "b7b1dd28dacb9958244f70f192e0eb90760c5d697cd07beb9ec2475a5e5d688a"
    url "https://github.com/idosaban-scaleops/flow/releases/download/v#{version}/flow_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "6c78d25a734493d93dc08a4433791d93b9bd4b56c056638dc1ab1a9dc35caa63"
      url "https://github.com/idosaban-scaleops/flow/releases/download/v#{version}/flow_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e95ef53b6dcaf23cf473844697fb914cce847bffb710389a6f080833467a6c17"
      url "https://github.com/idosaban-scaleops/flow/releases/download/v#{version}/flow_#{version}_linux_amd64.tar.gz"
    end
  end

  name "flow"
  desc "Personal workflow CLI for ticket-driven development"
  homepage "https://github.com/idosaban-scaleops/flow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flow"
  manpage "man/man1/flow.1"
  bash_completion "completions/flow.bash"
  fish_completion "completions/flow.fish"
  zsh_completion "completions/flow.zsh"

  # No zap stanza required
end
